  services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: catsgram
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  volumes:
  db_data: